spring.application.name=service-agendamento

# Servidor
server.port=8080

# Banco de Dados
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/agendamento_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true

# Logs para debug
logging.level.org.springframework.security=DEBUG

