type Query {
    consultas: [Consulta!]!
    consultasFuturas: [Consulta!]!
    consulta(id: ID!): Consulta
}

type Mutation {
    criarConsulta(input: ConsultaInput!): Consulta!
    editarConsulta(id: ID!, input: ConsultaInput!): Consulta!
    cancelarConsulta(id: ID!): Consulta!
    realizarConsulta(id: ID!): Consulta!
}

input ConsultaInput {
    pacienteId: ID!
    medicoId: ID!
    dataHora: String!
    observacoes: String
}

type Consulta {
    id: ID!
    paciente: Usuario!
    medico: Usuario!
    dataHora: String!
    status: String!
    observacoes: String
}

type Usuario {
    id: ID!
    username: String!
    nome: String!
    email: String!
    role: String!
}